name: Build & Deploy TaskTracker API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'   

      - name: Restore
        run: dotnet restore TaskTracker.Api/TaskTracker.Api.csproj

      - name: Build
        run: dotnet build TaskTracker.Api/TaskTracker.Api.csproj -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build

      - name: Publish
        run: dotnet publish TaskTracker.Api/TaskTracker.Api.csproj -c Release -o ./publish --no-build

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "TaskTracker-BootCamp"   # must match your Web App name exactly
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
